### ISSUE TITLE
Incluir as imagens com a execução dos programas.

### ISSUE THREAD

**Issue by fsantanna-uerj** [thiagoaslima/LP1#1]

**Comment by thiagoaslima** [comment]
desculpe, não estava ciente deste requisito.
devo fazê-lo para todos os códigos ou há algum em que isto é desnecessário?
providenciarei o mais rápido possível.

**Comment by fsantanna** [comment]
Comece a fazer a partir de agora...

**Comment by fsantanna** [comment]
(pode fechar essa issue)

**Comment by thiagoaslima** [comment]
obrigado
